/**
 * Appointment Tables Schema
 * Single Source of Truth for all appointment-related tables
 */

export const APPOINTMENT_TABLES = {
  appointments: {
    name: 'appointments',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      client_id: { type: 'uuid', nullable: false },
      staff_id: { type: 'uuid', nullable: false },
      service_id: { type: 'uuid', nullable: false },
      series_id: { type: 'uuid', nullable: true },
      created_by_profile_id: { type: 'uuid', nullable: false },
      // Scheduling
      start_at: { type: 'timestamptz', nullable: false },
      end_at: { type: 'timestamptz', nullable: false },
      time_zone: { type: 'time_zones', nullable: false },
      status: { type: 'appointment_status_enum', nullable: false, default: "'scheduled'" },
      // Location
      is_telehealth: { type: 'boolean', nullable: false, default: 'false' },
      location_name: { type: 'text', nullable: true },
      location_id: { type: 'uuid', nullable: true },
      // Billing Fields
      accept_assign: { type: 'boolean', nullable: true },
      auto_accident: { type: 'boolean', nullable: true },
      auto_accident_state: { type: 'text', nullable: true },
      employment_related: { type: 'boolean', nullable: true },
      prior_auth: { type: 'text', nullable: true },
      from_date_1: { type: 'date', nullable: true },
      thru_date_1: { type: 'date', nullable: true },
      place_of_service_1: { type: 'text', nullable: true },
      proc_code_1: { type: 'text', nullable: true },
      mod1_1: { type: 'text', nullable: true },
      mod2_1: { type: 'text', nullable: true },
      mod3_1: { type: 'text', nullable: true },
      mod4_1: { type: 'text', nullable: true },
      narrative_1: { type: 'text', nullable: true },
      units_1: { type: 'integer', nullable: true },
      charge_1: { type: 'numeric', nullable: true },
      remote_chgid_1: { type: 'text', nullable: true },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },

  appointment_series: {
    name: 'appointment_series',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      client_id: { type: 'uuid', nullable: false },
      staff_id: { type: 'uuid', nullable: false },
      service_id: { type: 'uuid', nullable: false },
      created_by_profile_id: { type: 'uuid', nullable: false },
      start_at: { type: 'timestamptz', nullable: false },
      duration_minutes: { type: 'integer', nullable: false },
      time_zone: { type: 'time_zones', nullable: false },
      rrule: { type: 'text', nullable: false },
      series_end_date: { type: 'date', nullable: true },
      max_occurrences: { type: 'integer', nullable: true },
      is_active: { type: 'boolean', nullable: false, default: 'true' },
      notes: { type: 'text', nullable: true },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },

  appointment_exceptions: {
    name: 'appointment_exceptions',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      series_id: { type: 'uuid', nullable: false },
      original_start_at: { type: 'timestamptz', nullable: false },
      change_type: { type: 'appointment_exception_type_enum', nullable: false },
      replacement_appointment_id: { type: 'uuid', nullable: true },
      notes: { type: 'text', nullable: true },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },

  appointment_session_context: {
    name: 'appointment_session_context',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      appointment_id: { type: 'uuid', nullable: false },
      client_location_desc: { type: 'text', nullable: true },
      client_location_state: { type: 'state_code_enum', nullable: true },
      emergency_contact_id: { type: 'uuid', nullable: true },
      emergency_plan_confirmed: { type: 'boolean', nullable: false, default: 'false' },
      emergency_plan_notes: { type: 'text', nullable: true },
      risk_level: { type: 'risk_level_enum', nullable: false, default: "'none'" },
      risk_notes: { type: 'text', nullable: true },
      context_captured_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },

  appointment_clinical_notes: {
    name: 'appointment_clinical_notes',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      appointment_id: { type: 'uuid', nullable: false },
      client_id: { type: 'uuid', nullable: false },
      staff_id: { type: 'uuid', nullable: false },
      // Clinical Assessment
      client_diagnosis: { type: 'text[]', nullable: false, default: "'{}'" },
      client_appearance: { type: 'text', nullable: true },
      client_attitude: { type: 'text', nullable: true },
      client_behavior: { type: 'text', nullable: true },
      client_speech: { type: 'text', nullable: true },
      client_affect: { type: 'text', nullable: true },
      client_mood: { type: 'text', nullable: true },
      client_thoughtprocess: { type: 'text', nullable: true },
      client_perception: { type: 'text', nullable: true },
      client_orientation: { type: 'text', nullable: true },
      client_memoryconcentration: { type: 'text', nullable: true },
      client_insightjudgement: { type: 'text', nullable: true },
      client_functioning: { type: 'text', nullable: true },
      // Risk Assessment
      client_substanceabuserisk: { type: 'client_substance_abuse_risk_enum', nullable: true },
      client_suicidalideation: { type: 'client_ideation_enum', nullable: true },
      client_homicidalideation: { type: 'client_ideation_enum', nullable: true },
      // Treatment Information
      client_prognosis: { type: 'text', nullable: true },
      client_progress: { type: 'text', nullable: true },
      client_sessionnarrative: { type: 'text', nullable: true },
      client_medications: { type: 'text', nullable: true },
      client_personsinattendance: { type: 'text', nullable: true },
      client_privatenote: { type: 'text', nullable: true },
      // Treatment Plan
      client_treatmentplan_startdate: { type: 'date', nullable: true },
      client_nexttreatmentplanupdate: { type: 'date', nullable: true },
      client_planlength: { type: 'text', nullable: true },
      client_treatmentfrequency: { type: 'text', nullable: true },
      client_problem: { type: 'text', nullable: true },
      client_treatmentgoal: { type: 'text', nullable: true },
      client_primaryobjective: { type: 'text', nullable: true },
      client_secondaryobjective: { type: 'text', nullable: true },
      client_tertiaryobjective: { type: 'text', nullable: true },
      client_intervention1: { type: 'text', nullable: true },
      client_intervention2: { type: 'text', nullable: true },
      client_intervention3: { type: 'text', nullable: true },
      client_intervention4: { type: 'text', nullable: true },
      client_intervention5: { type: 'text', nullable: true },
      client_intervention6: { type: 'text', nullable: true },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },
} as const;

export type AppointmentTable = keyof typeof APPOINTMENT_TABLES;
