/**
 * Core Patient/Client Tables Schema
 * Single Source of Truth for all client-related tables
 */

export const CORE_PATIENT_TABLES = {
  clients: {
    name: 'clients',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      profile_id: { type: 'uuid', nullable: false },
      pcn: { type: 'text', nullable: true },
      pat_name_f: { type: 'text', nullable: true },
      pat_name_m: { type: 'text', nullable: true },
      pat_name_l: { type: 'text', nullable: true },
      pat_name_preferred: { type: 'text', nullable: true },
      pat_dob: { type: 'date', nullable: true },
      pat_sex: { type: 'sex_enum', nullable: true },
      pat_gender_identity: { type: 'gender_identity_enum', nullable: true },
      email: { type: 'text', nullable: true },
      phone: { type: 'text', nullable: true },
      pat_addr_1: { type: 'text', nullable: true },
      pat_addr_2: { type: 'text', nullable: true },
      pat_city: { type: 'text', nullable: true },
      pat_state: { type: 'state_code_enum', nullable: true },
      pat_zip: { type: 'text', nullable: true },
      pat_country: { type: 'text', nullable: false, default: "'US'" },
      pat_ssn: { type: 'text', nullable: true },
      pat_marital_status: { type: 'text', nullable: true },
      pat_time_zone: { type: 'time_zones', nullable: true },
      pat_status: { type: 'pat_status_enum', nullable: true },
      pat_goal: { type: 'text', nullable: true },
      primary_staff_id: { type: 'uuid', nullable: true },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },

  client_diagnoses: {
    name: 'client_diagnoses',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      client_id: { type: 'uuid', nullable: false },
      diagnosis_code_id: { type: 'uuid', nullable: false },
      is_active: { type: 'boolean', nullable: false, default: 'true' },
      is_primary: { type: 'boolean', nullable: false, default: 'false' },
      added_at: { type: 'date', nullable: false, default: 'CURRENT_DATE' },
      resolved_at: { type: 'date', nullable: true },
      notes: { type: 'text', nullable: true },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },

  client_emergency_contacts: {
    name: 'client_emergency_contacts',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      client_id: { type: 'uuid', nullable: false },
      name: { type: 'text', nullable: false },
      relationship: { type: 'text', nullable: true },
      phone: { type: 'text', nullable: false },
      email: { type: 'text', nullable: true },
      addr_1: { type: 'text', nullable: true },
      addr_2: { type: 'text', nullable: true },
      city: { type: 'text', nullable: true },
      state: { type: 'state_code_enum', nullable: true },
      zip: { type: 'text', nullable: true },
      is_primary: { type: 'boolean', nullable: false, default: 'false' },
      is_active: { type: 'boolean', nullable: false, default: 'true' },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },

  client_insurance: {
    name: 'client_insurance',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      client_id: { type: 'uuid', nullable: false },
      payer_order: { type: 'text', nullable: false },
      is_active: { type: 'boolean', nullable: false, default: 'true' },
      effective_date: { type: 'date', nullable: true },
      termination_date: { type: 'date', nullable: true },
      // Insured Information
      ins_name_f: { type: 'text', nullable: true },
      ins_name_m: { type: 'text', nullable: true },
      ins_name_l: { type: 'text', nullable: true },
      ins_dob: { type: 'date', nullable: true },
      ins_sex: { type: 'sex_enum', nullable: true },
      ins_addr_1: { type: 'text', nullable: true },
      ins_addr_2: { type: 'text', nullable: true },
      ins_city: { type: 'text', nullable: true },
      ins_state: { type: 'state_code_enum', nullable: true },
      ins_zip: { type: 'text', nullable: true },
      ins_country: { type: 'text', nullable: false, default: "'US'" },
      ins_phone: { type: 'text', nullable: true },
      ins_employer: { type: 'text', nullable: true },
      // Policy Information
      ins_group: { type: 'text', nullable: true },
      ins_plan: { type: 'text', nullable: true },
      ins_number: { type: 'text', nullable: true },
      pat_rel: { type: 'pat_rel_enum', nullable: true },
      // Payer Information
      payer_name: { type: 'text', nullable: true },
      payerid: { type: 'text', nullable: true },
      payer_addr_1: { type: 'text', nullable: true },
      payer_addr_2: { type: 'text', nullable: true },
      payer_city: { type: 'text', nullable: true },
      payer_state: { type: 'state_code_enum', nullable: true },
      payer_zip: { type: 'text', nullable: true },
      payer_phone: { type: 'text', nullable: true },
      claims_office_number: { type: 'text', nullable: true },
      prior_auth: { type: 'text', nullable: true },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },

  client_safety_plans: {
    name: 'client_safety_plans',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      client_id: { type: 'uuid', nullable: false },
      created_by_profile_id: { type: 'uuid', nullable: false },
      plan_version: { type: 'integer', nullable: false, default: '1' },
      is_active: { type: 'boolean', nullable: false, default: 'true' },
      plan_title: { type: 'text', nullable: true },
      warning_signs: { type: 'text', nullable: true },
      internal_coping: { type: 'text', nullable: true },
      social_supports: { type: 'text', nullable: true },
      professional_contacts: { type: 'text', nullable: true },
      restricting_access: { type: 'text', nullable: true },
      crisis_steps: { type: 'text', nullable: true },
      reasons_for_living: { type: 'text', nullable: true },
      deactivated_at: { type: 'timestamptz', nullable: true },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },

  client_telehealth_consents: {
    name: 'client_telehealth_consents',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      client_id: { type: 'uuid', nullable: false },
      signed_by_profile_id: { type: 'uuid', nullable: false },
      consent_template_key: { type: 'text', nullable: false, default: "'telehealth_informed_consent'" },
      consent_template_version: { type: 'text', nullable: false, default: "'v1'" },
      signature_text: { type: 'text', nullable: false },
      signature_date: { type: 'date', nullable: false },
      signed_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      is_revoked: { type: 'boolean', nullable: false, default: 'false' },
      revoked_at: { type: 'timestamptz', nullable: true },
      document_id: { type: 'uuid', nullable: true },
      document_storage_path: { type: 'text', nullable: true },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },

  client_treatment_plans: {
    name: 'client_treatment_plans',
    columns: {
      id: { type: 'uuid', nullable: false, default: 'gen_random_uuid()' },
      tenant_id: { type: 'uuid', nullable: false },
      client_id: { type: 'uuid', nullable: false },
      staff_id: { type: 'uuid', nullable: false },
      created_by_profile_id: { type: 'uuid', nullable: false },
      plan_version: { type: 'integer', nullable: false, default: '1' },
      is_active: { type: 'boolean', nullable: false, default: 'true' },
      supersedes_plan_id: { type: 'uuid', nullable: true },
      plan_narrative: { type: 'text', nullable: true },
      treatmentplan_startdate: { type: 'date', nullable: true },
      next_treatmentplan_update: { type: 'date', nullable: true },
      planlength: { type: 'text', nullable: true },
      treatmentfrequency: { type: 'text', nullable: true },
      problem: { type: 'text', nullable: true },
      treatmentgoal: { type: 'text', nullable: true },
      primaryobjective: { type: 'text', nullable: true },
      secondaryobjective: { type: 'text', nullable: true },
      tertiaryobjective: { type: 'text', nullable: true },
      intervention1: { type: 'text', nullable: true },
      intervention2: { type: 'text', nullable: true },
      intervention3: { type: 'text', nullable: true },
      intervention4: { type: 'text', nullable: true },
      intervention5: { type: 'text', nullable: true },
      intervention6: { type: 'text', nullable: true },
      created_at: { type: 'timestamptz', nullable: false, default: 'now()' },
      updated_at: { type: 'timestamptz', nullable: false, default: 'now()' },
    },
  },
} as const;

export type CorePatientTable = keyof typeof CORE_PATIENT_TABLES;
