// Temporary database types until Supabase regenerates the types file
import type { BusinessAddress, TaxSettings, InvoiceSettings, PaymentSettings } from '@/utils/settingsValidation';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          tenant_id: string;
          role: 'business_admin' | 'contractor' | 'client';
          full_name: string | null;
          phone: string | null;
          email: string | null;
          company_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          tenant_id: string;
          role?: 'business_admin' | 'contractor' | 'client';
          full_name?: string | null;
          phone?: string | null;
          email?: string | null;
          company_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          tenant_id?: string;
          role?: 'business_admin' | 'contractor' | 'client';
          full_name?: string | null;
          phone?: string | null;
          email?: string | null;
          company_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          tenant_id: string;
          client_user_id: string | null;
          name: string;
          customer_type: 'residential' | 'commercial';
          phone: string | null;
          email: string | null;
          address: any | null;
          notes: string | null;
          created_by_user_id: string | null;
          assigned_to_user_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          client_user_id?: string | null;
          name: string;
          customer_type?: 'residential' | 'commercial';
          phone?: string | null;
          email?: string | null;
          address?: any | null;
          notes?: string | null;
          created_by_user_id?: string | null;
          assigned_to_user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          client_user_id?: string | null;
          name?: string;
          customer_type?: 'residential' | 'commercial';
          phone?: string | null;
          email?: string | null;
          address?: any | null;
          notes?: string | null;
          created_by_user_id?: string | null;
          assigned_to_user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      settings: {
        Row: {
          id: string;
          tenant_id: string;
          created_by_user_id: string;
          business_name: string | null;
          business_email: string | null;
          business_phone: string | null;
          business_website: string | null;
          business_address: BusinessAddress | null;
          logo_url: string | null;
          brand_color: string | null;
          text_color: string | null;
          tax_settings: TaxSettings | null;
          payment_settings: PaymentSettings | null;
          invoice_settings: InvoiceSettings | null;
          notification_settings: any | null;
          service_settings: any | null;
          business_hours: any | null;
          system_settings: any | null;
          user_preferences: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          created_by_user_id: string;
          business_name?: string | null;
          business_email?: string | null;
          business_phone?: string | null;
          business_website?: string | null;
          business_address?: BusinessAddress | null;
          logo_url?: string | null;
          brand_color?: string | null;
          text_color?: string | null;
          tax_settings?: TaxSettings | null;
          payment_settings?: PaymentSettings | null;
          invoice_settings?: InvoiceSettings | null;
          notification_settings?: any | null;
          service_settings?: any | null;
          business_hours?: any | null;
          system_settings?: any | null;
          user_preferences?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          created_by_user_id?: string;
          business_name?: string | null;
          business_email?: string | null;
          business_phone?: string | null;
          business_website?: string | null;
          business_address?: BusinessAddress | null;
          logo_url?: string | null;
          brand_color?: string | null;
          text_color?: string | null;
          tax_settings?: TaxSettings | null;
          payment_settings?: PaymentSettings | null;
          invoice_settings?: InvoiceSettings | null;
          notification_settings?: any | null;
          service_settings?: any | null;
          business_hours?: any | null;
          system_settings?: any | null;
          user_preferences?: any | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      services: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          description: string | null;
          default_price: number | null;
          duration_minutes: number | null;
          category: string | null;
          is_active: boolean;
          created_by_user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          description?: string | null;
          default_price?: number | null;
          duration_minutes?: number | null;
          category?: string | null;
          is_active?: boolean;
          created_by_user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          description?: string | null;
          default_price?: number | null;
          duration_minutes?: number | null;
          category?: string | null;
          is_active?: boolean;
          created_by_user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      job_series: {
        Row: {
          id: string;
          tenant_id: string;
          customer_id: string;
          title: string;
          description: string | null;
          service_id: string | null;
          recurrence_rule: string | null;
          start_date: string | null;
          active: boolean;
          created_by_user_id: string;
          assigned_to_user_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          customer_id: string;
          title: string;
          description?: string | null;
          service_id?: string | null;
          recurrence_rule?: string | null;
          start_date?: string | null;
          active?: boolean;
          created_by_user_id: string;
          assigned_to_user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          customer_id?: string;
          title?: string;
          description?: string | null;
          service_id?: string | null;
          recurrence_rule?: string | null;
          start_date?: string | null;
          active?: boolean;
          created_by_user_id?: string;
          assigned_to_user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      job_occurrences: {
        Row: {
          id: string;
          tenant_id: string;
          series_id: string | null;
          customer_id: string;
          title: string;
          description: string | null;
          service_id: string | null;
          start_at: string;
          end_at: string | null;
          status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          priority: 'low' | 'medium' | 'high' | 'urgent';
          notes: string | null;
          actual_cost: number | null;
          override_estimated_cost: number | null;
          created_by_user_id: string;
          assigned_to_user_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          series_id?: string | null;
          customer_id: string;
          title: string;
          description?: string | null;
          service_id?: string | null;
          start_at: string;
          end_at?: string | null;
          status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          notes?: string | null;
          actual_cost?: number | null;
          override_estimated_cost?: number | null;
          created_by_user_id: string;
          assigned_to_user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          series_id?: string | null;
          customer_id?: string;
          title?: string;
          description?: string | null;
          service_id?: string | null;
          start_at?: string;
          end_at?: string | null;
          status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          notes?: string | null;
          actual_cost?: number | null;
          override_estimated_cost?: number | null;
          created_by_user_id?: string;
          assigned_to_user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      quotes: {
        Row: {
          id: string;
          tenant_id: string;
          quote_number: string;
          customer_id: string;
          customer_name: string;
          job_id: string | null;
          issue_date: string;
          expiry_date: string | null;
          status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired';
          line_items: any;
          subtotal: number;
          tax_amount: number;
          total_amount: number;
          notes: string | null;
          terms: string | null;
          public_token: string | null;
          created_by_user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          quote_number: string;
          customer_id: string;
          customer_name: string;
          job_id?: string | null;
          issue_date: string;
          expiry_date?: string | null;
          status?: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired';
          line_items: any;
          subtotal: number;
          tax_amount: number;
          total_amount: number;
          notes?: string | null;
          terms?: string | null;
          public_token?: string | null;
          created_by_user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          quote_number?: string;
          customer_id?: string;
          customer_name?: string;
          job_id?: string | null;
          issue_date?: string;
          expiry_date?: string | null;
          status?: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired';
          line_items?: any;
          subtotal?: number;
          tax_amount?: number;
          total_amount?: number;
          notes?: string | null;
          terms?: string | null;
          public_token?: string | null;
          created_by_user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          tenant_id: string;
          invoice_number: string;
          customer_id: string;
          customer_name: string;
          job_id: string | null;
          issue_date: string;
          due_date: string;
          status: 'draft' | 'sent' | 'paid' | 'cancelled';
          line_items: any;
          subtotal: number;
          tax_amount: number;
          total_amount: number;
          amount_paid: number;
          notes: string | null;
          terms: string | null;
          public_token: string | null;
          payment_status: 'pending' | 'paid' | 'failed' | 'cancelled';
          created_by_user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          invoice_number: string;
          customer_id: string;
          customer_name: string;
          job_id?: string | null;
          issue_date: string;
          due_date: string;
          status?: 'draft' | 'sent' | 'paid' | 'cancelled';
          line_items: any;
          subtotal: number;
          tax_amount: number;
          total_amount: number;
          amount_paid?: number;
          notes?: string | null;
          terms?: string | null;
          public_token?: string | null;
          payment_status?: 'pending' | 'paid' | 'failed' | 'cancelled';
          created_by_user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          invoice_number?: string;
          customer_id?: string;
          customer_name?: string;
          job_id?: string | null;
          issue_date?: string;
          due_date?: string;
          status?: 'draft' | 'sent' | 'paid' | 'cancelled';
          line_items?: any;
          subtotal?: number;
          tax_amount?: number;
          total_amount?: number;
          amount_paid?: number;
          notes?: string | null;
          terms?: string | null;
          public_token?: string | null;
          payment_status?: 'pending' | 'paid' | 'failed' | 'cancelled';
          created_by_user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_permissions: {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          access_jobs: boolean;
          access_customers: boolean;
          access_services: boolean;
          access_quotes: boolean;
          access_invoicing: boolean;
          access_calendar: boolean;
          access_settings: boolean;
          access_user_management: boolean;
          send_quotes: boolean;
          supervisor: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          access_jobs?: boolean;
          access_customers?: boolean;
          access_services?: boolean;
          access_quotes?: boolean;
          access_invoicing?: boolean;
          access_calendar?: boolean;
          access_settings?: boolean;
          access_user_management?: boolean;
          send_quotes?: boolean;
          supervisor?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          user_id?: string;
          access_jobs?: boolean;
          access_customers?: boolean;
          access_services?: boolean;
          access_quotes?: boolean;
          access_invoicing?: boolean;
          access_calendar?: boolean;
          access_settings?: boolean;
          access_user_management?: boolean;
          send_quotes?: boolean;
          supervisor?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {
      get_user_tenant_id: {
        Args: {};
        Returns: string;
      };
    };
    Enums: {
      user_role: 'business_admin' | 'contractor' | 'client';
      customer_type: 'residential' | 'commercial';
    };
  };
}